spring.application.name=eduConnect

spring.ai.ollama.base-url=http://localhost:11434

spring.ai.ollama.chat.model=tinyllama
spring.ai.ollama.chat.options.temperature=0.7
spring.ai.ollama.chat.options.max-tokens=512

spring.ai.ollama.embedding.model=nomic-embed-text

uploadDir=src/main/resources/static/uploadPdfs/users


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
spring.servlet.multipart.file-size-threshold=2KB


logging.level.org.springframework.ai=DEBUG

logging.level.org.springframework.security=DEBUG

logging.level.com.example.educonnect=DEBUG


spring.datasource.url=jdbc:postgresql://localhost:5432/ragdb
spring.datasource.username=youssef
spring.datasource.password=Salah@1957

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.datasource.hikari.maximum-pool-size=10

jwt.secret=dGhpcyBpcyBhIHZlcnkgc2VjdXJlIHNlY3JldCBrZXkgZm9yIGp3dCB0b2tlbiBnZW5lcmF0aW9uLi4uLg==
jwt.expiration=3600000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=elrhadiry@gmail.com
spring.mail.password=bdildtpehdxbjllh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
